# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'WSUV-Twitter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!



   pod 'Alamofire', '~> 4.4'
   pod 'SSKeychain'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

pod 'AlamofireNetworkActivityIndicator', '~> 2.0'


  # Pods for WSUV-Twitter

  target 'WSUV-TwitterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WSUV-TwitterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
